---
title: CPAN Challenge Stats
output: html_document
---

```{r, include=FALSE}
library('ggplot2')
library('dplyr')
library('knitr')
library('tidyr')
library('reshape2')
library('jsonlite')

challenges   <- fromJSON( "./challenges.json", )
tally        <- challenges %>% group_by(date) %>% summarize( challenges = n(), success = sum(done>0) )
tally_melted <- melt(tally, vars=c("challenges","success") )
```

## Challenges, month by month

```{r, echo = FALSE}
ggplot( tally_melted, aes(  date, value, color=variable) ) + geom_point()
```

### Completion rates

```{r, echo = FALSE}
tally$percent_success <- tally$success / tally$challenges
ggplot( tally, aes( date, percent_success ) ) + geom_point()
```

## List of participants 

All in all, there are been a total of `r length(unique(challenges$assignee))`
participants.

```{r, echo = FALSE}
p <- challenges %>% 
        group_by(assignee) %>% 
        filter( done ) %>% 
        summarize( months=n(), earliest=first(date), latest=last(date) ) %>% 
        arrange(desc( months),desc(latest))

knitr::kable( p, caption = "all participants"  )
```

```{r, echo=FALSE}

ggplot(p, mapping=aes(months)) + geom_histogram()
```

## PR stats 

```{r, echo=FALSE}

prs  <- fromJSON('./prs.json')

```

Over `r nrow(prs)` PRs were generated over the span of the CPAN Challenge.

```{r}

barplot(table(prs$state),main="state of PRs")

```

